Web3Auth/web3auth-swift-sdk

OpenloginSwiftSdkDemo/OpenloginSwiftSdkDemo/ContentView.swift
Sources/OpenLogin/WebAuth.swift

should not be merged before https://github.com/torusresearch/openlogin-sdk-frontend/pull/9

feat: implement sign out by disabling fast login

---

OpenloginSwiftSdkDemo/OpenloginSwiftSdkDemo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Sources/Web3Auth/Types.swift
Sources/Web3Auth/Web3AuthUserInfo.swift
Web3Auth.podspec

- Also remove some resuide from the renaming

feat: add dapp share

---

Sources/Web3Auth/Types.swift

mfa level added @chaitanyapotti @metallicalfa2 please have a look

mfa level added

---

Sources/Web3Auth/Web3Auth.swift
Sources/Web3Auth/Web3AuthUserInfo.swift

id token added in userInfo in web3authState

id token added

---

Web3authSwiftSdkDemo/Web3authSwiftSdkDemo.xcodeproj/project.pbxproj
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ContentView.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/LoggedInView.swift

Sample app UI improved

---

README.md

readme ver update

---

Sources/Web3Auth/Network.swift
Sources/Web3Auth/SessionManagement.swift
Sources/Web3Auth/Types.swift
Sources/Web3Auth/Web3Auth.swift
Sources/Web3Auth/Web3AuthState.swift
Tests/Web3AuthTests/Web3AuthTests.swift
Web3Auth.podspec
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo.xcodeproj/project.pbxproj
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ContentView.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/LoginView.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/UserDetailView.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

coreKitKey and coreKitEd25519PrivKey added in Web3AuthState

coreKitKey and coreKitEd25519PrivKey added in Web3AuthState

---

Package.resolved
Package.swift
Web3Auth.podspec
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

bump session manager swift sdk

bump session manager swift sdk

---

Sources/Web3Auth/Types.swift

feat: update openlogin version to v6

feat: update openlogin version to v6

---

Sources/Web3Auth/Web3Auth.swift

fix url component bug

---

Sources/Web3Auth/WebViewController.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

* Webview enhancements for closing wallet services.
https://github.com/Web3Auth/web3auth-swift-sdk/assets/44719313/2f134024-aee6-4506-954a-00f2698055c2

feat: webview enhancements for closing wallet services.

---

Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

Sign example updated.

---

Sources/Web3Auth/Web3Auth.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

Additionally ensures WebViewController runs on the main thread.

fix: extra variable in launchWalletServices call

---

Sources/Web3Auth/Types.swift
Sources/Web3Auth/Web3Auth.swift
Sources/Web3Auth/WebViewController.swift

Update enableMFA function for extraLoginOptions

update enableMFA function for extraLoginOptions

---

Sources/Web3Auth/Web3Auth.swift
Sources/Web3Auth/Web3AuthError.swift

* mfaAlreadyEnabled check added

mfaAlreadyEnabled check added

---

Sources/Web3Auth/Types.swift
Sources/Web3Auth/Web3Auth.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

* Added some improvements wrt schemas

added some improvements wrt schemas

---

Sources/Web3Auth/Types.swift
Sources/Web3Auth/Web3Auth.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

* Remove loginParams parameter in launchWalletServices() function

feat: remove loginParams parameter in launchWalletServices() function

---

Sources/Web3Auth/Web3Auth.swift

fix: remove invalid session if found

---

Web3Auth.podspec

Update to podspec missed in #76. Tag and release as 10.0.1

Update podspec 10.0.1

---

Sources/Web3Auth/Web3Auth.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

* Single source redirect url. 
* If redirect url is null, setting it to initparams redirectUrl instead some random value

Single source redirect url.

---

Sources/Web3Auth/Web3Auth.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

enableMFA function BugFix.
Jira Link:
1) Since W3ALoginParams is optional parameter in enableMFA function. So we have to always rely upon initParams redirectUrl for redirect fucntionality in enableMFA. Otherwise needs to make W3ALoginParams mandatory in enableMFA() too.
On emulator.

enableMFA function bugFix.

---

Package.swift
Web3Auth.podspec

* Bump session-manager sdk and podspec

bump session-manager sdk and podspec

---

Sources/Web3Auth/Types.swift

Jira Link: https://toruslabs.atlassian.net/browse/DEVREL-1134?atlOrigin=eyJpIjoiOTIxZjk4NTdhMjYwNGYxMGE3ZDhmNzdkZjBlYjNjNjAiLCJwIjoiaiJ9
Update max sessionTime to 30 days instead of 7 days
N/A

Update max sessionTime

---

Sources/Web3Auth/Web3Auth.swift
Sources/Web3Auth/WebViewController.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

* BugFix: Add appState in signMessageMap
* Feature: Add onCancel() event in WebViewController
Jira Link: https://toruslabs.atlassian.net/browse/PD-4336
* BugFix: Add appState in signMessageMap
* Feature: Add onCancel() event in WebViewController
* On Emulator

Add appState in signMessageMap

---

Sources/Web3Auth/Types.swift

fix: email_passwordless login type

---

Sources/Web3Auth/Types.swift
Sources/Web3Auth/Web3Auth.swift
Sources/Web3Auth/Web3AuthError.swift
Web3Auth.podspec
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/UserDetailView.swift
Web3authSwiftSdkDemo/Web3authSwiftSdkDemo/ViewModel.swift

Jira Link: https://toruslabs.atlassian.net/browse/PD-4387
* manageMFA function added
* In emulator
https://github.com/user-attachments/assets/1064cf40-1283-445f-ba8d-3661477d8d89

manageMFA function added
